# Generated by Django 5.0.6 on 2026-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tomado', 'Tomado'), ('nao_tomado', 'Não tomado'), ('excluido', 'Excluído')], max_length=12, verbose_name='Tipo de Evento')),
                ('nome_medicamento', models.CharField(max_length=200, verbose_name='Nome do Medicamento')),
                ('dose', models.CharField(max_length=200, verbose_name='Dose')),
                ('importancia', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10, verbose_name='Nível de Importância')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações do Medicamento')),
                ('observacao_registro', models.TextField(blank=True, default='', verbose_name='Observação do Registro')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Evento do Histórico',
                'verbose_name_plural': 'Eventos do Histórico',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
